name: Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew buildNamed
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Simple Gems
        path: build/outputJar
